//AddWatchWindowVars Build 2
expRemoveAll()
//Variables
expAdd ("VIENNA_buildInfo",getNatural())
expAdd ("VIENNA_boardStatus",getNatural())
expAdd ("VIENNA_clearTrip", getNatural())
expAdd ("VIENNA_iLRef_pu",getNatural())
expAdd ("VIENNA_closeGiLoop",getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
expAdd ("EPwm2Regs.TZFLG",getNatural())
expAdd ("EPwm3Regs.TZFLG",getNatural())
expAdd ("VIENNA_guiVbus_Volts",getNatural())
expAdd ("VIENNA_guiVbusPM_Volts",getNatural())
expAdd ("VIENNA_guiVbusMN_Volts",getNatural())
expAdd ("VIENNA_guiVrms1_Volts",getNatural())
expAdd ("VIENNA_guiVrms2_Volts",getNatural())
expAdd ("VIENNA_guiVrms3_Volts",getNatural())
expAdd ("VIENNA_guiIrms1_Amps",getNatural())
expAdd ("VIENNA_guiIrms2_Amps",getNatural())
expAdd ("VIENNA_guiIrms3_Amps",getNatural())
expAdd ("VIENNA_guiPF1",getNatural())
expAdd ("VIENNA_guiPF2",getNatural())
expAdd ("VIENNA_guiPF3",getNatural())